import {cart, addToCart} from '../data/cart.js';
import {products} from '../data/products.js';
import {formatCurrency} from './utils/money.js';

/*
productsHTML saves HTML code generated by forEach() used on products array.
*/
let productsHTML = '';

/*
forEach() generates HTML code for each product from products array.
*/
products.forEach((product) => {
  productsHTML += `
    <div class="product-container">
      <div class="product-image-container">
        <img class="product-image"
          src="${product.image}">
      </div>

      <div class="product-name limit-text-to-2-lines">
        ${product.name}
      </div>

      <div class="product-rating-container">
        <img class="product-rating-stars"
          src="images/ratings/rating-${product.rating.stars * 10}.png">
        <div class="product-rating-count link-primary">
          ${product.rating.count}
        </div>
      </div>

      <div class="product-price">
        $${formatCurrency(product.priceCents)}
      </div>

      <div class="product-quantity-container">
        <select class="js-quantity-selector-${product.id}">
          <option selected value="1">1</option>
          <option value="2">2</option>
          <option value="3">3</option>
          <option value="4">4</option>
          <option value="5">5</option>
          <option value="6">6</option>
          <option value="7">7</option>
          <option value="8">8</option>
          <option value="9">9</option>
          <option value="10">10</option>
        </select>
      </div>

      <div class="product-spacer"></div>

      <div class="added-to-cart js-added-to-cart-${product.id}">
        <img src="images/icons/checkmark.png">
        Added
      </div>

      <button class="add-to-cart-button 
      button-primary js-add-to-cart"
      data-product-id="${product.id}">
        Add to Cart
      </button>
    </div>
  `;
});

/*
Put productsHTML in <div> marked with 'js-products-grid' class.
*/
document.querySelector('.js-products-grid').innerHTML = productsHTML;

function updateCartQuantity() {
  let cartQuantity = 0;

  // Sum up total quantity of all products in the cart.
  cart.forEach((cartItem) => {
    cartQuantity += cartItem.quantity;
  });

  // Show cart quantity in top right corner of the page.
  document.querySelector('.js-cart-quantity').innerHTML = cartQuantity;
}

/*
Show 'Added' message on amazon.html page after clicking Add to Cart button.
*/
function showAddedMessage(productId) {
  // Get <div> element with "Added" message.
  const addedMessage = document.querySelector(`.js-added-to-cart-${productId}`);

  // Show "Added" message.
  addedMessage.classList.add('added-to-cart-visible');

  // Hide "Added" message after 2 seconds.
  setTimeout(() => {
    addedMessage.classList.remove('added-to-cart-visible');
  }, 2000);
}

/*
Click Event Listener for Add to Cart buttons.
*/
document.querySelectorAll('.js-add-to-cart')
  .forEach((button) => {
    button.addEventListener('click', () => {
      const {productId} = button.dataset;

      addToCart(productId);
      updateCartQuantity();
      showAddedMessage(productId);
    });
  });